name: pr-build
on:
  workflow_dispatch:
    inputs:
      pr:
        description: upstream branch to pull from
        type: string
        required: true

jobs:
  docker-alpine:
    uses: ./.github/workflows/docker-pr.yml
    with:
      upstream: alpine-develop
      pr: ${{ inputs.pr }}
      tags: alpine-pr-${{ inputs.pr }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker-hwaccel:
    uses: ./.github/workflows/docker-pr.yml
    with:
      upstream: hwaccel-develop
      pr: ${{ inputs.pr }}
      tags: hwaccel-pr-${{ inputs.pr }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}